import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { getAppName } from "@/lib/app";
import { ToastProvider } from "@/components/ui/toast";
import { CustomToast } from "@/components/ui/custom-toast";

/* const sailec = localFont({
  src: "./fonts/sailec.woff2",
  variable: "--font-sailec",
  weight: "100 900",
  style: "normal",
}); */

const sailec = localFont({
  src: [
    { path: "./fonts/sailec/Sailec-Thin.ttf", weight: "100", style: "normal" },
    { path: "./fonts/sailec/sailec-light.woff2", weight: "300", style: "normal" },
    { path: "./fonts/sailec/sailec-regular.otf", weight: "400", style: "normal" },
    { path: "./fonts/sailec/Sailec-Medium.ttf", weight: "500", style: "normal" },
    // { path: "./fonts/sailec/Sailec-SemiBold.woff2", weight: "600", style: "normal" },
    { path: "./fonts/sailec/sailec-bold.woff2", weight: "700", style: "normal" },
    // { path: "./fonts/sailec/Sailec-ExtraBold.woff2", weight: "800", style: "normal" },
    { path: "./fonts/sailec/sailec-black.ttf", weight: "900", style: "normal" },
  ],
  variable: "--font-sailec"
});

export const metadata: Metadata = {
  title: {
    template: "%s | " + (getAppName() ?? "App Name"),
    default: "App Name",
  },
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${sailec.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem={true}
          storageKey="presentation-app-theme"
        >
          {children}
          <CustomToast />
        </ThemeProvider>
      </body>
    </html>
  );
}
