# Use Node 20-alpine as base image
FROM node:20-alpine

# Install tsx globally
RUN npm install tsx -g

# Set working directory
WORKDIR /api

# Copy application files
COPY src/api ./

# Install dependencies
RUN npm install

# Expose the port the app runs on
EXPOSE 3001

# Start the application in development mode
CMD ["npm", "run", "start:dev"]